compilar :

buscaporimagem: g++ -o buscaporimagem buscaporimagem.cpp  -O3 -march=native -std=c++0x

wincompilar :

buscaporimagem: g++ buscaporimagem.cpp -o buscaporimagem.exe -O3 -march=native -std=c++0x